version: '2'

services:
  nexus:
    image: sonatype/nexus3
    volumes:
      - "C:\\Users\\Richard.Hannah\\nugetrepo\\nexus-data:/nexus-data"
    ports: 
      - "0.0.0.0:8081:8081"
  jenkins:
     build:
      context: ./jenkins
      dockerfile: Dockerfile
     ports:
       - "0.0.0.0:8080:8080"